### PR TITLE
CI changes

### PR DESCRIPTION
**Pull request by Margen67**

### CODE REVIEW

**Comment by andrewbird** [comment]
So what's the benefit of removing the step name from upload-artifact?

**Comment by Margen67** [comment]
> 
> 
> So what's the benefit of removing the step name from upload-artifact?

The name is less specific.

**Comment by andrewbird** [comment]
So we get  `Run actions/upload-artifact@v2` as a line item in the build log instead of `upload`. Are you intending to change `package install`, `build` and `test` too?

**Comment by Margen67** [comment]
> 
> 
> So we get `Run actions/upload-artifact@v2` as a line item in the build log instead of `upload`. Are you intending to change `package install`, `build` and `test` too?

No.

**Comment by andrewbird** [comment]
@Margen67 commit bc260b0 is good, can you drop the other two please?

**Comment by andrewbird** [comment]
Thanks.

@PerditionC this it fine to merge now, thanks.

**Pull request merged**
