### PR TITLE
Resurrected Pr177

### PR DESCRIPTION
**Pull request by andrewbird**
This is @jmalak's PR rescued from a fork that was deleted before it could be applied.

### CODE REVIEW

**Comment by PerditionC** [comment]
moving utils part I don't plan to apply, but the correction to usage I do want to apply.  Not sure how to properly split the PR, so I may just manually apply the patch.

**Comment by ecm-pushbx** [comment]
Longer comment on the original PR: https://github.com/FDOS/kernel/pull/177#issuecomment-2295033931

**Comment by andrewbird** [comment]
I've split it now, and will apply.

**Comment by PerditionC** [comment]
thank you

**Pull request merged**
