### PR TITLE
ecm 2022-05 (exeflat copies CONFIG block, add debugger config/support, add kernel command line with commands CONFIG/ALTCONFIG/OLDCONFIG, fix empty executable)

### PR DESCRIPTION
**Pull request by ecm-pushbx**
The kernel command line can be set by bootable lDebug using a command like the following to load the kernel: `boot protocol=freedos cmdline=1 kernel.sys // config=testconf.sys`

I submitted [a pull request to dosemu2](https://github.com/dosemu2/dosemu2/pull/1635) to add support for setting the RxDOS/FreeDOS kernel command line but it was rejected.

### CODE REVIEW

**Comment by PerditionC** [comment]
I will look at this tonight.  I don't expect any issues, just not around a computer

**Comment by ecm-pushbx** [comment]
OW has some errors. I will look into those later today or tomorrow.

**Comment by andrewbird** [comment]
There were also warnings from GCC about printed args.

**Comment by ecm-pushbx** [comment]
> There were also warnings from GCC about printf args.

I didn't see any warnings building either with the CI build script or using `make clean COMPILER=gcc` then `make all COMPILER=gcc XUPX=` Can you quote the warnings you get?

**Comment by andrewbird** [comment]
They are in exeflat with both GCC and watcom. Sorry can't link now, on mobile.

**Comment by ecm-pushbx** [comment]
> They are in exeflat with both GCC and watcom. Sorry can't link now, on mobile.

Please do so later, using my 2021-11-13 gcc-ia16 I don't get any warnings on this machine (Debian amd64 server).

**Comment by ecm-pushbx** [comment]
No need actually those are just mistakes on my part. Copied around something and messed up (`printf` with unused varargs parameter).

**Comment by andrewbird** [comment]
Looking better, just a couple of %lu Vs %u mismatches now.

**Comment by ecm-pushbx** [comment]
Fixed all the errors and warnings for OW in the CI build and hopefully also the `printf` warnings. Odd that I didn't get these warnings at all but should be fixed too. It appears that exeflat builds with the host's gcc for the native gcc-ia16 build as well as the CI gcc-ia16 and CI OpenWatcom builds. This is the compiler I'm using:

```
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
```

**Comment by ecm-pushbx** [comment]
> Looking better, just a couple of %lu Vs %u mismatches now.

Fixed those two. Apparently the `gcc` used for compiling exeflat.c on our system does not get `-Wall` by default. Passing that explicitly compiling just that file manually did bring up the warnings you mentioned. Perhaps this could be added to the makefiles? I'm not sure where to look for this though.

**Comment by andrewbird** [comment]
It looks like you'd need to add -Wall to the CLT variable in mkfiles/gcc.mak and mkfiles/owlinux.mak

**Comment by ecm-pushbx** [comment]
> It looks like you'd need to add -Wall to the CLT variable in mkfiles/gcc.mak and mkfiles/owlinux.mak

@PerditionC Do you want this?

**Pull request merged**
